title: NFDI4Microbiota Knowledge Base
author:
  name: 'Github User'
  email: 'github@example.com'
description: >- # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
#baseurl: /nfdi4microbiota-knowledge-base

excerpts:
  # Displays or hides post excerpts from home layout post listing.
  show: true
  # Cuts off excerpts with an ellipsis (...) after 32 words (approx. 2 lines).
  # You can also leave this false, and manually control excerpt length:
  # https://jekyllrb.com/docs/posts/#post-excerpts
  auto_truncate: true

# Theme configuration
bootstrap:
  # Theme date format
  # refer to https://shopify.github.io/liquid/filters/date/ if you want to customize this
  date_format: "%b %-d, %Y"

  # If you want to link only specific pages in your header, uncomment
  # this and add the path to the page *files* in order as they should show up
  #header_pages:
  # - about.md

  # generate social links in footer
  social_links:
    mastodon: 'https://nfdi.social/@NFDI4Microbiota'
    github:  'https://github.com/NFDI4Microbiota'


# Build settings
exclude:
  - node_modules
remote_theme: jonaharagon/jekyll-bootstrap-theme
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jemoji
  - jekyll-redirect-from
  - jekyll-last-modified-at
  - jekyll-scholar
markdown: Kramdown
collections_dir: docs
collections:
  Getting-Started:
    output: true
    permalink: /:collection/:name.html
    order:
     - 01-introduction.md
     - contributing.md
     - contributors.md
     - privacy-policy-english-translation.md
  Research-Data-Management:
    output: true
    permalink: /:collection/:name.html
    order:
     - rd.md
     - rdm.md
     - md.md
     - fair.md
     - os.md
     - gsp.md
     - policies.md
     - rdm-in-industry.md
  RDM-Plan:
    output: true
    permalink: /:collection/:name.html
    order:
     - dmp.md
     - preregistration.md
  RDM-Collect:
    output: true
    permalink: /:collection/:name.html
    order:
     - data-creation.md
     - informed-consent.md
     - eln.md
     - data-qc.md
  RDM-Process:
    output: true
    permalink: /:collection/:name.html
    order:
     - data-organization.md
     - file-formats.md
     - data-documentation.md
     - data-standardization.md
  RDM-Preserve:
    output: true
    permalink: /:collection/:name.html
    order:
     - aruna-object-storage.md
     - digital-preservation.md
  RDM-Share:
    output: true
    permalink: /:collection/:name.html
    order:
     - data-security.md
     - collaboration-tools.md
     - pids.md
     - data-publishing.md
     - data-repositories.md
     - licenses.md
     - privacy-issues.md
  RDM-Reuse:
    output: true
    permalink: /:collection/:name.html
    order:
     - research-data-commons.md
     - data-reuse.md
  Reproducible-Data-Analysis:
    output: true
    permalink: /:collection/:name.html
    order:
     - workflows.md
     - software-containers.md
     - resources.md
  Software-Development:
    output: true
    permalink: /:collection/:name.html
    order:
     - smp.md
     - toolsurvey.md
  Experimental-SOPs:
    output: true
    permalink: /:collection/:name.html
    order:
     - sop-template.md
     - introduction.md
     - external-sops.md
     - viral-purification-from-bacterial-culture.md
     - dna-and-rna-kits-by-sample.md
     - lipid-and-fatty-acid-extraction-protocol-from-biological-samples.md
     - metabolite-extraction-from-adherent-mammalian-cells.md
     - metabolite-extraction-from-plant-tissue.md
     - proteomics-tmt-labelled-sp3-method.md
     - sample-collection-and-storage-by-sample.md
     - media-freezing-faecal-samples-recultivation.md
     - biobank-fmt-samples.md
     - godon-dna-extraction.md
  Resources:
    output: true
    permalink: /:collection/:name.html
    order:
     - glossary.md
     - external-training-resources.md
     - host-associated-isolates.md
  How-We-Operate:
    output: true
    permalink: /:collection/:name.html
    order:
     - n4m-intro.md
     - governance-workflows.md
     - privacy-policy-english-translation.md
     - training-guidelines.md

collection_order:
  - Getting-Started
  - Research-Data-Management
  - RDM-Plan
  - RDM-Collect
  - RDM-Process
  - RDM-Preserve
  - RDM-Share
  - RDM-Reuse
  - Reproducible-Data-Analysis
  - Software-Development
  - Experimental-SOPs
  - Resources
  - How-We-Operate

# Plugin settings
scholar:
# Numeric style like american-medical-association causes duplication in numbering of the references
# So enforcing a author-year style
  style: apa
  source: ./docs/_bibliography
  bibtex_filters:
    - latex
    - markdown
