title: NFDI4Microbiota Knowledge Base
author:
  name: 'Github User'
  email: 'github@example.com'
description: >- # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
#baseurl: /nfdi4microbiota-knowledge-base

excerpts:
  # Displays or hides post excerpts from home layout post listing.
  show: true
  # Cuts off excerpts with an ellipsis (...) after 32 words (approx. 2 lines).
  # You can also leave this false, and manually control excerpt length:
  # https://jekyllrb.com/docs/posts/#post-excerpts
  auto_truncate: true

# Theme configuration
bootstrap:
  # Theme date format
  # refer to https://shopify.github.io/liquid/filters/date/ if you want to customize this
  date_format: "%b %-d, %Y"

  # If you want to link only specific pages in your header, uncomment
  # this and add the path to the page *files* in order as they should show up
  #header_pages:
  # - about.md

  # generate social links in footer
  social_links:
    twitter: 'https://twitter.com/jonaharagon'
    github:  'https://github.com/jonaharagon'
    #facebook: 'https://example.com/@jekyllrb'
    #instagram: 'https://example.com/@jekyllrb'
    #linkedin: 'https://example.com/@jekyllrb'
    #google: 'https://example.com/@jekyllrb'
    #youtube: 'https://example.com/@jekyllrb'
    #twitch: 'https://example.com/@jekyllrb'
    #telegram: 'https://example.com/@jekyllrb'
    #whatsapp: 'https://example.com/@jekyllrb'
    #discord: 'https://example.com/@jekyllrb'
    #slack: 'https://example.com/@jekyllrb'


# Build settings
exclude:
  - node_modules
remote_theme: jonaharagon/jekyll-bootstrap-theme
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jemoji
  - jekyll-redirect-from
markdown: Kramdown
collections_dir: docs
collections:
  Getting-Started:
    output: true
    permalink: /:collection/:name
    order:
      - introduction.md
      - contributing.md
      - contributors.md
  Research-Data-Management:
    output: true
    permalink: /:collection/:name
    order: 2
  Reproducible-Data-Analysis:
    output: true
    permalink: /:collection/:name
    order: 3
  Software-Development:
    output: true
    permalink: /:collection/:name
    order: 4
  Experimental-Procedure-Standards-SOPs:
    output: true
    permalink: /:collection/:name
    order: 5
  Resources:
    output: true
    permalink: /:collection/:name
    order: 6
  How-We-Operate:
    output: true
    permalink: /:collection/:name
    order: 7

# Plugin settings
scholar:
# Numeric style like american-medical-association causes duplication in numbering of the references
# So enforcing a author-year style
  style: apa
  source: ./docs/_bibliography
