name: Lint Markdown file

on:
  # Runs on pushes targeting the default branch
  push:
    branches: ["main"]

  # Run on pull request
  pull_request:
    branches: ["main"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  # Lint Markdown file job
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: DavidAnson/markdownlint-cli2-action@v17
      with:
      # Lint all markdown files in the repo
        globs: '**/*.md'
        # Automatically fix supported issues
        fix: true
        rules: '~MD013'